### ISSUE TITLE
Migrate database job

### ISSUE THREAD

**Issue by saylerb** [twplatformlabs/lab-api-teams#28]
### Context

We're using [gorm](https://gorm.io/index.html) as an ORM, which comes with some "automigration" features out of the box. This is sufficient for quick prototyping, but we may feel some pain as the application data model grows, and we need a robust way of ensuring the database schema is changed at the right time during each deployment. 

**Scope:** Create a way to trigger a database migration during each deployment that is compatible with a cloud-native environment where we have multiple replicas.

**Out of scope:** research and select a dedicated database migration tool (go-migrate, goose) for more robust migrations.

### Possible solutions

* Run migrations manually from our workstations - this is what we're currently doing, not much explanation needed for why this is not ideal
* Run migrations programmatically when application starts
* Run migrations as a separate process, triggered by CI, prior to deployment of new source code ✅ 

### Other considerations

* Any tests that require a database could continue to use GORM's automigration, since they shouldn't need to test database versioning
* A separate Job running within the cluster to migrate the database will cause additional artifacts to be created (binaries, Docker images). We may need to consider cleaning up old ones if we have limited 

### Tasks

- [x] parameterize the database Port number
- [x] familiarize with current yugabyte deployment using sandbox cluster
- [x] separate yugabyte deployment from database creation
- [x] add retries to database creation script to handle variable time it takes to resolve DNS of new database service when it starts up
- [x] create and publish new migration binary and docker Image
- [x] test creation of Kubernetes migration Job in sandbox
- [x] release Kubernetes job
- [x] ensure `docker-compose` is compatible with `goreleaser` workflow
